name: uShop
depends: [Vault]
soft-depends: [Essentials]
author: Linus122
main: xyz.spaceio.ushop.Main
version: ${project.version}
description: easy sell your stuff
commands:
   ushop:
      description: main command of ushop
      usage: /<command>
      permission: ushop.admin